### ISSUE TITLE
Git clone is not working

### ISSUE THREAD

**Issue by HermesSantos** [albingroen/quick.nvim#15]
![image](https://github.com/albingroen/quick.nvim/assets/94411142/bd6f3d49-0bc0-4f96-8b2c-cce5d935167e)
im on windows 11, i downloaded it using the zip file but i think that alowing to clone it would be better.

**Comment by albingroen** [comment]
Try if this works!

```
git clone https://github.com/albingroen/quick.nvim.git
```

**Comment by HermesSantos** [comment]
It works, thank you
