### ISSUE TITLE
Packer command not found

### ISSUE THREAD

**Issue by Fakecrafter** [albingroen/quick.nvim#2]
I followed the instructions...
Then I opened nvim and typed :PackerInstall and it says that the command is not found.
I restarted the installation and the computer. same thing
I installed the AUR package for packer and tried again. nothing
I have the newest nvim 0.6 installed and I run Arch Linux.
When you open neovim it gives an error that it couldnt find tokyonight (obviously cuz its not installed). 
I don't know what to do now...

**Comment by yoryer** [comment]
If you already have Packer installed you need to do a previous step.

On the init.lua file from the line 1 to the line 17 the config file is already trying to use some of the plugins, but these aren't installed yet, so what you need to do are the following steps: 
1. Comment from the line 1 to 17
2. Source the file on nvim
3. If you are not facing new errors, you should be able to execute PackerInstall
4. Once the dependencies are installed you can uncomment the lines from 1 to 17 and source the file again and everything should load and work just fine.

Hope this helps!

**Comment by Fakecrafter** [comment]
Thx
