### ISSUE TITLE
PackerInstall not a editor command

### ISSUE THREAD

**Issue by levitabris** [albingroen/quick.nvim#3]
I moved my old config to `~/.config/nvim.old` and followed the steps to install Packer and the config file. My Neovim doesn't recognize `:PackerInstall`. 

There is also a startup error message
```
Error detected while processing /Users/xxx/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/xxx/.config/nvim/lua/colors.lua:2: Vim(colorscheme):E185: Cannot find color scheme 'tokyonight'
stack traceback:
        [C]: in function 'cmd'
        /Users/xxx/.config/nvim/lua/colors.lua:2: in main chunk
        [C]: in function 'require'
        /Users/xxx/.config/nvim/init.lua:2: in main chunk
Press ENTER or type command to continue
```

Does anyone have the same problem? Help~

Edit: I running neovim on macOS 12.1, `nvim -v` output
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info
```

**Comment by albingroen** [comment]
Have your tried running `:PackerSync` and see if that works?

**Comment by albingroen** [comment]
Regarding the startup error, I think if you pull down the latest changes from GitHub, it should be fixed now!

**Comment by arthur322** [comment]
I had the same problem. Fixed following the instructions from this issue https://github.com/albingroen/quick.nvim/issues/2

**Comment by levitabris** [comment]
> I had the same problem. Fixed following the instructions from this issue #2

This really solves my problem. You have saved me a LOT of hours. Thanks.

**Comment by albingroen** [comment]
I've added a note about this in the README now!

https://github.com/albingroen/quick.nvim#2-install-plugins
